#!/usr/bin/env python3
"""
font_small_block.py
-------------------
Small Block font from patorjk's TAAG (https://patorjk.com/software/taag/),
TAAG calls it "Small Block"; in figlet/pyfiglet it's named `smblock`.

Each glyph is 4 rows tall, 3 cols wide (most characters), with a few
narrower glyphs (`I`, `!`, `.`, `'`, ` `) that are auto-padded to 3 cols.
There is no inter-character gap — glyphs are concatenated directly.

The dictionary below was generated by rendering each character with
pyfiglet on the host machine. To re-fetch or add characters:

    pip install pyfiglet
    python3 -c "import pyfiglet; print(pyfiglet.figlet_format('X', font='smblock'))"

then paste the output between the triple quotes for that character.
Whitespace-only entries are treated as unfilled placeholders and skipped
silently; the renderer falls back to '???' for any character that isn't
defined.
"""

# ── Geometry ────────────────────────────────────────────────────────────────
ROWS = 4
COLS = 3   # every glyph must end up exactly this wide after padding


# ── Glyph table ─────────────────────────────────────────────────────────────
_RAW = {
    # ── Space ───────────────────────────────────────────────────────────────
    ' ': """




""",

    # ── Digits ──────────────────────────────────────────────────────────────
    '0': """
▞▀▖
▌▞▌
▛ ▌
▝▀
""",
    '1': """
▗▌
 ▌
 ▌
▝▀
""",
    '2': """
▞▀▖
 ▗▘
▗▘
▀▀▘
""",
    '3': """
▞▀▖
 ▄▘
▖ ▌
▝▀
""",
    '4': """
▌ ▌
▚▄▌
  ▌
  ▘
""",
    '5': """
▛▀▘
▙▄
▖ ▌
▝▀
""",
    '6': """
▞▀▖
▙▄
▌ ▌
▝▀
""",
    '7': """
▛▀▌
 ▐
 ▌
 ▘
""",
    '8': """
▞▀▖
▚▄▘
▌ ▌
▝▀
""",
    '9': """
▞▀▖
▚▄▌
▖ ▌
▝▀
""",

    # ── Punctuation ─────────────────────────────────────────────────────────
    '/': """
  ▌
 ▞
▞
▘
""",
    '!': """
▐
▐
▝
▝
""",
    '?': """
▞▀▖
 ▗▘
 ▘
 ▘
""",
    '.': """


▗▖
▝▘
""",
    '-': """

▄▄▖


""",
    '>': """
▖
▝▚▖
▞▘

""",
    "'": """
▝▌
▝


""",

    # ── Uppercase A–Z ───────────────────────────────────────────────────────
    'A': """
▞▀▖
▙▄▌
▌ ▌
▘ ▘
""",
    'B': """
▛▀▖
▙▄▘
▌ ▌
▀▀
""",
    'C': """
▞▀▖
▌
▌ ▖
▝▀
""",
    'D': """
▛▀▖
▌ ▌
▌ ▌
▀▀
""",
    'E': """
▛▀▘
▙▄
▌
▀▀▘
""",
    'F': """
▛▀▘
▙▄
▌
▘
""",
    'G': """
▞▀▖
▌▄▖
▌ ▌
▝▀
""",
    'H': """
▌ ▌
▙▄▌
▌ ▌
▘ ▘
""",
    'I': """
▜▘
▐
▐
▀▘
""",
    'J': """
 ▜▘
 ▐
▌▐
▝▘
""",
    'K': """
▌ ▌
▙▞
▌▝▖
▘ ▘
""",
    'L': """
▌
▌
▌
▀▀▘
""",
    'M': """
▙▗▌
▌▘▌
▌ ▌
▘ ▘
""",
    'N': """
▙ ▌
▌▌▌
▌▝▌
▘ ▘
""",
    'O': """
▞▀▖
▌ ▌
▌ ▌
▝▀
""",
    'P': """
▛▀▖
▙▄▘
▌
▘
""",
    'Q': """
▞▀▖
▌ ▌
▌▚▘
▝▘▘
""",
    'R': """
▛▀▖
▙▄▘
▌▚
▘ ▘
""",
    'S': """
▞▀▖
▚▄
▖ ▌
▝▀
""",
    'T': """
▀▛▘
 ▌
 ▌
 ▘
""",
    'U': """
▌ ▌
▌ ▌
▌ ▌
▝▀
""",
    'V': """
▌ ▌
▚▗▘
▝▞
 ▘
""",
    'W': """
▌ ▌
▌▖▌
▙▚▌
▘ ▘
""",
    'X': """
▌ ▌
▝▞
▞▝▖
▘ ▘
""",
    'Y': """
▌ ▌
▝▞
 ▌
 ▘
""",
    'Z': """
▀▀▌
 ▞
▞
▀▀▘
""",
}


# ── Cook the raw dict into rectangular glyphs ───────────────────────────────
def _cook(raw):
    out = {}
    for ch, blob in raw.items():
        # Whitespace-only blob = unfilled placeholder; skip silently.
        # Exception: ' ' is intentionally all-whitespace and must be kept.
        if ch != ' ' and not blob.strip():
            continue
        # Split on newlines and drop only the leading/trailing empty
        # lines that come from the triple-quote syntax. Inner blank lines
        # are kept (needed for ' ', '.', '-', etc.).
        lines = blob.split('\n')
        if lines and lines[0] == '':
            lines = lines[1:]
        if lines and lines[-1] == '':
            lines = lines[:-1]
        if len(lines) != ROWS:
            raise ValueError(
                f"glyph {ch!r}: expected {ROWS} rows, got {len(lines)}: {lines!r}"
            )
        cooked = []
        for r in lines:
            if len(r) > COLS:
                raise ValueError(
                    f"glyph {ch!r} row {r!r} is wider than COLS={COLS}"
                )
            cooked.append(r.ljust(COLS))
        out[ch] = cooked
    return out


FONT    = _cook(_RAW)
UNKNOWN = ['?' * COLS] * ROWS   # fallback for missing glyphs


# ── Renderer ────────────────────────────────────────────────────────────────
def render(text):
    """Return a list of ROWS strings, the pixel-font rendering of `text`.

    Unknown characters render as boxes of '?' so gaps are obvious.
    """
    rows = [''] * ROWS
    for ch in text:
        glyph = FONT.get(ch, FONT.get(ch.upper(), UNKNOWN))
        for r in range(ROWS):
            rows[r] += glyph[r]
    return rows


# ── Self-test ───────────────────────────────────────────────────────────────
if __name__ == '__main__':
    samples = [
        '20/20',
        'WHAT WILL SQUIRTLE DO?',
        'BULBASAUR FAINTED!',
        'YOU WIN!',
        'FIGHT  BAG  POKEMON  RUN',
        '0123456789',
        'ABCDEFGHIJKLM',
        'NOPQRSTUVWXYZ',
    ]
    for s in samples:
        print(f"\nrender({s!r}):")
        for r in render(s):
            print(f"  {r}")
    print(f"\nDefined glyphs ({len(FONT)}): {''.join(sorted(FONT.keys()))}")
    print(f"Each glyph: {ROWS} rows × {COLS} cols")
